### ISSUE TITLE
As a developer I want descriptive warnings when I'm missing textResourceBindings

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#318]
### Description

When developing an application, and my app is missing the expected `textResourceBindings` as should be defined in my form layout file, the app can in some circumstances end up with the dreaded 'unknown error occurred'. Instead of getting a show-stopping error message with a cryptic trace in the console, I'd rather have the frontend tell me which component is missing which key in `textResourceBinding`, in some way. Preferably directly in the UI, or at least in the browser console.

For some components where the binding key is optional, I'd possibly prefer a weaker warning/info message in the browser console telling me about this possible problem, without showing that warning in the app user interface.

### Additional Information

[Background/discussion on Slack](https://altinndevops.slack.com/archives/CDU1S3NLW/p1656407853828659)

**Comment by FinnurO** [comment]
Also related to an issue in Studio repo where missing textbindings causes PDF generation to crash. This should be adressed in the root cause.

**Comment by bjosttveit** [comment]
This is solved now, right?

**Comment by olemartinorg** [comment]
@bjosttveit I think it mostly is, yes. I talked about 'unknown error' here, so I assume frontend crashed in those cases. Probably because of null errors, so this might have been fixed as early as #597. But we still don't have mechanisms for making text resources required, so some components may be misconfigured to the point where they can't work properly (i.e. a `Paragraph` does not make sense when the text in it is optional).
